version: "3.9"

networks:
  localdev:
    name: localdev

services:
  main-api:
    build:
      context: .
      dockerfile: Metinvest.API/Dockerfile
    restart: always
    ports:
      - "7000:80"
    environment:
      - ConnectionStrings__Default=Server=sqlServer1;Database=MetinvestDb;User ID=sa;Password=Database.01;
    depends_on:
      - sqlServer
    networks:
      - localdev
  
  sqlServer:
    container_name: sqlServer1
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Database.01"
      ACCEPT_EULA: "Y"
    networks:
      - localdev